name: SpigotDash
description: A Webinterface that can make Monitoring your Server much easier
version: 0.4.2 BETA
main: de.tobias.spigotdash.main
api-version: 1.13
author: Tobias Dickes
softdepend:
    - Skript
commands:
    dashurl: